name: Create Release

on: push

jobs:
  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --production
    - run: ls ./lib/bindings/
    - run: ls ./lib/bindings/napi-v5/
    - run: ./node_modules/.bin/node-pre-gyp build
    - name: Package Binary
      run: ./node_modules/.bin/node-pre-gyp package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/stage/*.tar.gz

  build-ubuntu:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - run: ls -R /usr/lib/
    - run: ls -R /usr/lib64/
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --production
    - run: ./node_modules/.bin/node-pre-gyp rebuild
    - name: Package Binary
      run: ./node_modules/.bin/node-pre-gyp package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/stage/*.tar.gz

  build-macos:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --production
    - run: ./node_modules/.bin/node-pre-gyp rebuild
    - name: Package Binary
      run: ./node_modules/.bin/node-pre-gyp package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/stage/*.tar.gz

  create-release:

    runs-on: ubuntu-latest

    needs: [build-ubuntu, build-macos]

    steps:

    - uses: actions/checkout@v2

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Create Release 
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.current-version }}
        release_name: ${{ steps.package-version.outputs.current-version }}
        draft: true
        prerelease: false

    - uses: actions/download-artifact@v2
      with:
        name: binaries

    # Upload the various binaries

    - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v3.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v3.tar.gz
        asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v3.tar.gz
        asset_content_type: application/gzip

    - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v4.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v4.tar.gz
        asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v4.tar.gz
        asset_content_type: application/gzip

    - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v5.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v5.tar.gz
        asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-darwin-x64-napi-v5.tar.gz
        asset_content_type: application/gzip

    # - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v3.tar.gz
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v3.tar.gz
    #     asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v3.tar.gz
    #     asset_content_type: application/gzip

    # - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v4.tar.gz
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v4.tar.gz
    #     asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v4.tar.gz
    #     asset_content_type: application/gzip

    # - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v5.tar.gz
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v5.tar.gz
    #     asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-win32-x64-napi-v5.tar.gz
    #     asset_content_type: application/gzip

    - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v3.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v3.tar.gz
        asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v3.tar.gz
        asset_content_type: application/gzip

    - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v4.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v4.tar.gz
        asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v4.tar.gz
        asset_content_type: application/gzip

    - name: Upload odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v5.tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v5.tar.gz
        asset_name: odbc-v${{ steps.package-version.outputs.current-version }}-linux-x64-napi-v5.tar.gz
        asset_content_type: application/gzip
